INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME) VALUES ('123','Dunder Mifflin Paper Company');
INSERT INTO CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME) VALUES ('456','Microsfot');

INSERT INTO ITEM (ITEM_ID,ITEM_PRICE) VALUES ('1',1.5);
INSERT INTO ITEM (ITEM_ID,ITEM_PRICE) VALUES ('2',2.5);
INSERT INTO ITEM (ITEM_ID,ITEM_PRICE) VALUES ('3',3.5);
INSERT INTO ITEM (ITEM_ID,ITEM_PRICE) VALUES ('4',4.5);


